<a href="https://colab.research.google.com/github/manish2509/Machine-Learning-Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [6]:
import numpy as np

#One Dimensional Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
#ndim returns the dimension of the array
print(arr.ndim)

[1 2 3 4 5]
1


In [7]:
#Two Dimensional Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
#Three Dimensional Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [9]:
#Indexing starts from o to n
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])
#This will return the sum of 3rd and 4th element in the array

7


#Slicing

#Slicing in python means taking elements from one given index to another given index.We pass slice instead of index like this: [start:end].We can also define the step, like this: [start:end:step].

In [11]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[1:5:2])

[2 3 4 5]
[5 6 7]
[2 4]


#Shape
#NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


#Sorting

In [13]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#Sorting

In [15]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


Which means that the value 4 is present at index 3, 5, and 6.